export type TMEntry = {
  id: string;
  name: string;
  type: string;
  power: number;
  accuracy: number;
  category: "Physical" | "Special" | "Status";
};

export const TM_DATABASE: TMEntry[] = [
  { id: "TM001", name: "Acrobatics", type: "Flying", power: 55, accuracy: 100, category: "Physical" },
  { id: "TM002", name: "Astonish", type: "Ghost", power: 30, accuracy: 100, category: "Physical" },
  { id: "TM003", name: "Avalanche", type: "Ice", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM004", name: "Bind", type: "Normal", power: 15, accuracy: 85, category: "Physical" },
  { id: "TM005", name: "Blizzard", type: "Ice", power: 110, accuracy: 70, category: "Special" },
  { id: "TM006", name: "Body Press", type: "Fighting", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM007", name: "Body Slam", type: "Normal", power: 85, accuracy: 100, category: "Physical" },
  { id: "TM008", name: "Bounce", type: "Flying", power: 85, accuracy: 85, category: "Physical" },
  { id: "TM009", name: "Brave Bird", type: "Flying", power: 120, accuracy: 100, category: "Physical" },
  { id: "TM010", name: "Brick Break", type: "Fighting", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM011", name: "Brine", type: "Water", power: 65, accuracy: 100, category: "Special" },
  { id: "TM012", name: "Brutal Swing", type: "Dark", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM013", name: "Bubble Beam", type: "Water", power: 65, accuracy: 100, category: "Special" },
  { id: "TM014", name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM015", name: "Bug Buzz", type: "Bug", power: 90, accuracy: 100, category: "Special" },
  { id: "TM016", name: "Bulldoze", type: "Ground", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM017", name: "Bullet Seed", type: "Grass", power: 25, accuracy: 100, category: "Physical" },
  { id: "TM018", name: "Charge Beam", type: "Electric", power: 50, accuracy: 90, category: "Special" },
  { id: "TM019", name: "Chilling Water", type: "Water", power: 50, accuracy: 100, category: "Special" },
  { id: "TM020", name: "Close Combat", type: "Fighting", power: 120, accuracy: 100, category: "Physical" },
  { id: "TM021", name: "Crunch", type: "Dark", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM022", name: "Cut", type: "Normal", power: 50, accuracy: 95, category: "Physical" },
  { id: "TM023", name: "Dark Pulse", type: "Dark", power: 80, accuracy: 100, category: "Special" },
  { id: "TM024", name: "Dazzling Gleam", type: "Fairy", power: 80, accuracy: 100, category: "Special" },
  { id: "TM025", name: "Dig", type: "Ground", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM026", name: "Dive", type: "Water", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM027", name: "Double-Edge", type: "Normal", power: 120, accuracy: 100, category: "Physical" },
  { id: "TM028", name: "Draco Meteor", type: "Dragon", power: 130, accuracy: 90, category: "Special" },
  { id: "TM029", name: "Dragon Breath", type: "Dragon", power: 60, accuracy: 100, category: "Special" },
  { id: "TM030", name: "Dragon Claw", type: "Dragon", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM031", name: "Dragon Pulse", type: "Dragon", power: 85, accuracy: 100, category: "Special" },
  { id: "TM032", name: "Dragon Tail", type: "Dragon", power: 60, accuracy: 90, category: "Physical" },
  { id: "TM033", name: "Drain Punch", type: "Fighting", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM034", name: "Draining Kiss", type: "Fairy", power: 50, accuracy: 100, category: "Special" },
  { id: "TM035", name: "Dream Eater", type: "Psychic", power: 100, accuracy: 100, category: "Special" },
  { id: "TM036", name: "Dual Wingbeat", type: "Flying", power: 40, accuracy: 90, category: "Physical" },
  { id: "TM037", name: "Dynamic Punch", type: "Fighting", power: 100, accuracy: 50, category: "Physical" },
  { id: "TM038", name: "Earth Power", type: "Ground", power: 90, accuracy: 100, category: "Special" },
  { id: "TM039", name: "Earthquake", type: "Ground", power: 100, accuracy: 100, category: "Physical" },
  { id: "TM040", name: "Echoed Voice", type: "Normal", power: 40, accuracy: 100, category: "Special" },
  { id: "TM041", name: "Egg Bomb", type: "Normal", power: 100, accuracy: 75, category: "Physical" },
  { id: "TM042", name: "Electroweb", type: "Electric", power: 55, accuracy: 95, category: "Special" },
  { id: "TM043", name: "Energy Ball", type: "Grass", power: 90, accuracy: 100, category: "Special" },
  { id: "TM044", name: "Expanding Force", type: "Psychic", power: 80, accuracy: 100, category: "Special" },
  { id: "TM045", name: "Explosion", type: "Normal", power: 250, accuracy: 100, category: "Physical" },
  { id: "TM046", name: "Facade", type: "Normal", power: 70, accuracy: 100, category: "Physical" },
  { id: "TM047", name: "False Swipe", type: "Normal", power: 40, accuracy: 100, category: "Physical" },
  { id: "TM048", name: "Fire Blast", type: "Fire", power: 110, accuracy: 85, category: "Special" },
  { id: "TM049", name: "Fire Fang", type: "Fire", power: 65, accuracy: 95, category: "Physical" },
  { id: "TM050", name: "Fire Punch", type: "Fire", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM051", name: "Fire Spin", type: "Fire", power: 35, accuracy: 85, category: "Special" },
  { id: "TM052", name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, category: "Special" },
  { id: "TM053", name: "Flash Cannon", type: "Steel", power: 80, accuracy: 100, category: "Special" },
  { id: "TM054", name: "Fly", type: "Flying", power: 90, accuracy: 95, category: "Physical" },
  { id: "TM055", name: "Focus Blast", type: "Fighting", power: 120, accuracy: 70, category: "Special" },
  { id: "TM056", name: "Focus Punch", type: "Fighting", power: 150, accuracy: 100, category: "Physical" },
  { id: "TM057", name: "Foul Play", type: "Dark", power: 95, accuracy: 100, category: "Physical" },
  { id: "TM058", name: "Freeze-Dry", type: "Ice", power: 70, accuracy: 100, category: "Special" },
  { id: "TM059", name: "Frost Breath", type: "Ice", power: 60, accuracy: 90, category: "Special" },
  { id: "TM060", name: "Giga Drain", type: "Grass", power: 75, accuracy: 100, category: "Special" },
  { id: "TM061", name: "Giga Impact", type: "Normal", power: 150, accuracy: 90, category: "Physical" },
  { id: "TM062", name: "Heat Wave", type: "Fire", power: 95, accuracy: 90, category: "Special" },
  { id: "TM063", name: "Hex", type: "Ghost", power: 65, accuracy: 100, category: "Special" },
  { id: "TM064", name: "Hidden Power", type: "Normal", power: 60, accuracy: 100, category: "Special" },
  { id: "TM065", name: "High Horsepower", type: "Ground", power: 95, accuracy: 95, category: "Physical" },
  { id: "TM066", name: "Hurricane", type: "Flying", power: 110, accuracy: 70, category: "Special" },
  { id: "TM067", name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, category: "Special" },
  { id: "TM068", name: "Hyper Beam", type: "Normal", power: 150, accuracy: 90, category: "Special" },
  { id: "TM069", name: "Hyper Voice", type: "Normal", power: 90, accuracy: 100, category: "Special" },
  { id: "TM070", name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, category: "Special" },
  { id: "TM071", name: "Ice Fang", type: "Ice", power: 65, accuracy: 95, category: "Physical" },
  { id: "TM072", name: "Ice Punch", type: "Ice", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM073", name: "Ice Spinner", type: "Ice", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM074", name: "Icicle Spear", type: "Ice", power: 25, accuracy: 100, category: "Physical" },
  { id: "TM075", name: "Icy Wind", type: "Ice", power: 55, accuracy: 95, category: "Special" },
  { id: "TM076", name: "Incinerate", type: "Fire", power: 60, accuracy: 100, category: "Special" },
  { id: "TM077", name: "Infestation", type: "Bug", power: 20, accuracy: 100, category: "Special" },
  { id: "TM078", name: "Iron Head", type: "Steel", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM079", name: "Iron Tail", type: "Steel", power: 100, accuracy: 75, category: "Physical" },
  { id: "TM080", name: "Leaf Blade", type: "Grass", power: 90, accuracy: 100, category: "Physical" },
  { id: "TM081", name: "Leaf Storm", type: "Grass", power: 130, accuracy: 90, category: "Special" },
  { id: "TM082", name: "Leech Life", type: "Bug", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM083", name: "Liquidation", type: "Water", power: 85, accuracy: 100, category: "Physical" },
  { id: "TM084", name: "Low Sweep", type: "Fighting", power: 65, accuracy: 100, category: "Physical" },
  { id: "TM085", name: "Mega Drain", type: "Grass", power: 40, accuracy: 100, category: "Special" },
  { id: "TM086", name: "Mega Kick", type: "Normal", power: 120, accuracy: 75, category: "Physical" },
  { id: "TM087", name: "Mega Punch", type: "Normal", power: 80, accuracy: 85, category: "Physical" },
  { id: "TM088", name: "Mud Shot", type: "Ground", power: 55, accuracy: 95, category: "Special" },
  { id: "TM089", name: "Mud-Slap", type: "Ground", power: 20, accuracy: 100, category: "Special" },
  { id: "TM090", name: "Mystical Fire", type: "Fire", power: 75, accuracy: 100, category: "Special" },
  { id: "TM091", name: "Outrage", type: "Dragon", power: 120, accuracy: 100, category: "Physical" },
  { id: "TM092", name: "Overheat", type: "Fire", power: 130, accuracy: 90, category: "Special" },
  { id: "TM093", name: "Pay Day", type: "Normal", power: 40, accuracy: 100, category: "Physical" },
  { id: "TM094", name: "Payback", type: "Dark", power: 50, accuracy: 100, category: "Physical" },
  { id: "TM095", name: "Phantom Force", type: "Ghost", power: 90, accuracy: 100, category: "Physical" },
  { id: "TM096", name: "Pin Missile", type: "Bug", power: 25, accuracy: 95, category: "Physical" },
  { id: "TM097", name: "Play Rough", type: "Fairy", power: 90, accuracy: 90, category: "Physical" },
  { id: "TM098", name: "Pluck", type: "Flying", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM099", name: "Poison Jab", type: "Poison", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM100", name: "Poison Tail", type: "Poison", power: 50, accuracy: 100, category: "Physical" },
  { id: "TM101", name: "Pollen Puff", type: "Bug", power: 90, accuracy: 100, category: "Special" },
  { id: "TM102", name: "Pounce", type: "Bug", power: 50, accuracy: 100, category: "Physical" },
  { id: "TM103", name: "Power Gem", type: "Rock", power: 80, accuracy: 100, category: "Special" },
  { id: "TM104", name: "Power-Up Punch", type: "Fighting", power: 40, accuracy: 100, category: "Physical" },
  { id: "TM105", name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, category: "Special" },
  { id: "TM106", name: "Psychic", type: "Psychic", power: 90, accuracy: 100, category: "Special" },
  { id: "TM107", name: "Psychic Fangs", type: "Psychic", power: 85, accuracy: 100, category: "Physical" },
  { id: "TM108", name: "Psyshock", type: "Psychic", power: 80, accuracy: 100, category: "Special" },
  { id: "TM109", name: "Rage", type: "Normal", power: 20, accuracy: 100, category: "Physical" },
  { id: "TM110", name: "Razor Wind", type: "Normal", power: 80, accuracy: 100, category: "Special" },
  { id: "TM111", name: "Retaliate", type: "Normal", power: 70, accuracy: 100, category: "Physical" },
  { id: "TM112", name: "Rock Blast", type: "Rock", power: 25, accuracy: 90, category: "Physical" },
  { id: "TM113", name: "Rock Climb", type: "Normal", power: 90, accuracy: 85, category: "Physical" },
  { id: "TM114", name: "Rock Slide", type: "Rock", power: 75, accuracy: 90, category: "Physical" },
  { id: "TM115", name: "Rock Smash", type: "Fighting", power: 40, accuracy: 100, category: "Physical" },
  { id: "TM116", name: "Rock Tomb", type: "Rock", power: 60, accuracy: 95, category: "Physical" },
  { id: "TM117", name: "Round", type: "Normal", power: 60, accuracy: 100, category: "Special" },
  { id: "TM118", name: "Sand Tomb", type: "Ground", power: 35, accuracy: 85, category: "Physical" },
  { id: "TM119", name: "Scald", type: "Water", power: 80, accuracy: 100, category: "Special" },
  { id: "TM120", name: "Secret Power", type: "Normal", power: 70, accuracy: 100, category: "Physical" },
  { id: "TM121", name: "Seed Bomb", type: "Grass", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM122", name: "Self-Destruct", type: "Normal", power: 200, accuracy: 100, category: "Physical" },
  { id: "TM123", name: "Shadow Ball", type: "Ghost", power: 80, accuracy: 100, category: "Special" },
  { id: "TM124", name: "Shadow Claw", type: "Ghost", power: 70, accuracy: 100, category: "Physical" },
  { id: "TM125", name: "Silver Wind", type: "Bug", power: 60, accuracy: 100, category: "Special" },
  { id: "TM126", name: "Sky Attack", type: "Flying", power: 140, accuracy: 90, category: "Physical" },
  { id: "TM127", name: "Sky Drop", type: "Flying", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM128", name: "Sludge Bomb", type: "Poison", power: 90, accuracy: 100, category: "Special" },
  { id: "TM129", name: "Sludge Wave", type: "Poison", power: 95, accuracy: 100, category: "Special" },
  { id: "TM130", name: "Smack Down", type: "Rock", power: 50, accuracy: 100, category: "Physical" },
  { id: "TM131", name: "Snarl", type: "Dark", power: 55, accuracy: 95, category: "Special" },
  { id: "TM132", name: "Solar Beam", type: "Grass", power: 120, accuracy: 100, category: "Special" },
  { id: "TM133", name: "Solar Blade", type: "Grass", power: 125, accuracy: 100, category: "Physical" },
  { id: "TM134", name: "Steel Wing", type: "Steel", power: 70, accuracy: 90, category: "Physical" },
  { id: "TM135", name: "Stomping Tantrum", type: "Ground", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM136", name: "Stone Edge", type: "Rock", power: 100, accuracy: 80, category: "Physical" },
  { id: "TM137", name: "Struggle Bug", type: "Bug", power: 50, accuracy: 100, category: "Special" },
  { id: "TM138", name: "Submission", type: "Fighting", power: 80, accuracy: 80, category: "Physical" },
  { id: "TM139", name: "Surf", type: "Water", power: 90, accuracy: 100, category: "Special" },
  { id: "TM140", name: "Tackle", type: "Normal", power: 40, accuracy: 100, category: "Physical" },
  { id: "TM141", name: "Tail Slap", type: "Normal", power: 25, accuracy: 85, category: "Physical" },
  { id: "TM142", name: "Take Down", type: "Normal", power: 90, accuracy: 85, category: "Physical" },
  { id: "TM143", name: "Thief", type: "Dark", power: 60, accuracy: 100, category: "Physical" },
  { id: "TM144", name: "Thunder", type: "Electric", power: 110, accuracy: 70, category: "Special" },
  { id: "TM145", name: "Thunder Fang", type: "Electric", power: 65, accuracy: 95, category: "Physical" },
  { id: "TM146", name: "Thunder Punch", type: "Electric", power: 75, accuracy: 100, category: "Physical" },
  { id: "TM147", name: "Thunderbolt", type: "Electric", power: 90, accuracy: 100, category: "Special" },
  { id: "TM148", name: "Trailblaze", type: "Grass", power: 50, accuracy: 100, category: "Physical" },
  { id: "TM149", name: "Tri Attack", type: "Normal", power: 80, accuracy: 100, category: "Special" },
  { id: "TM150", name: "U-turn", type: "Bug", power: 70, accuracy: 100, category: "Physical" },
  { id: "TM151", name: "Uproar", type: "Normal", power: 90, accuracy: 100, category: "Special" },
  { id: "TM152", name: "Vacuum Wave", type: "Fighting", power: 40, accuracy: 100, category: "Special" },
  { id: "TM153", name: "Venoshock", type: "Poison", power: 65, accuracy: 100, category: "Special" },
  { id: "TM154", name: "Volt Switch", type: "Electric", power: 70, accuracy: 100, category: "Special" },
  { id: "TM155", name: "Water Fall", type: "Water", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM156", name: "Water Gun", type: "Water", power: 40, accuracy: 100, category: "Special" },
  { id: "TM157", name: "Water Pledge", type: "Water", power: 80, accuracy: 100, category: "Special" },
  { id: "TM158", name: "Water Pulse", type: "Water", power: 60, accuracy: 100, category: "Special" },
  { id: "TM159", name: "Weather Ball", type: "Normal", power: 50, accuracy: 100, category: "Special" },
  { id: "TM160", name: "Whirlpool", type: "Water", power: 35, accuracy: 85, category: "Special" },
  { id: "TM161", name: "Wild Charge", type: "Electric", power: 90, accuracy: 100, category: "Physical" },
  { id: "TM162", name: "X-Scissor", type: "Bug", power: 80, accuracy: 100, category: "Physical" },
  { id: "TM163", name: "Zap Cannon", type: "Electric", power: 120, accuracy: 50, category: "Special" },
  { id: "TM164", name: "Zen Headbutt", type: "Psychic", power: 80, accuracy: 90, category: "Physical" },
];

export function tmPrice(power: number): number {
  if (power >= 100) return 4000;
  if (power >= 75) return 3000;
  return 2000;
}

export function tmStoreItems() {
  return TM_DATABASE.map((tm) => ({
    name: `${tm.id} ${tm.name}`,
    price: tmPrice(tm.power),
    info: `${tm.type} · ${tm.power} pwr · ${tm.accuracy} acc · ${tm.category}`,
  }));
}
