import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const TOTAL = 1025;
const CONCURRENCY = 30;

const TYPE_MAP = {
  normal: "Normal", fire: "Fire", water: "Water", electric: "Electric",
  grass: "Grass", ice: "Ice", fighting: "Fighting", poison: "Poison",
  ground: "Ground", flying: "Flying", psychic: "Psychic", bug: "Bug",
  rock: "Rock", ghost: "Ghost", dragon: "Dragon", dark: "Dark",
  steel: "Steel", fairy: "Fairy",
};

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const titleMove = (s) => s.split("-").map(cap).join(" ");

async function fetchJSON(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return await r.json();
    } catch (e) {
      if (i === retries - 1) throw e;
      await new Promise((r) => setTimeout(r, 500 * (i + 1)));
    }
  }
}

async function fetchPokemon(id) {
  const p = await fetchJSON(`https://pokeapi.co/api/v2/pokemon/${id}`);
  const stats = Object.fromEntries(p.stats.map((s) => [s.stat.name, s.base_stat]));
  const types = p.types.sort((a, b) => a.slot - b.slot).map((t) => TYPE_MAP[t.type.name] || cap(t.type.name));

  const damaging = p.moves.filter((m) =>
    m.version_group_details.some((v) => v.move_learn_method.name === "level-up")
  );
  damaging.sort((a, b) => {
    const al = Math.min(...a.version_group_details.filter((v) => v.move_learn_method.name === "level-up").map((v) => v.level_learned_at || 99));
    const bl = Math.min(...b.version_group_details.filter((v) => v.move_learn_method.name === "level-up").map((v) => v.level_learned_at || 99));
    return bl - al;
  });
  const moveNames = [...new Set(damaging.slice(0, 6).map((m) => titleMove(m.move.name)))].slice(0, 4);
  while (moveNames.length < 1) moveNames.push("Tackle");

  const name = p.name.split("-").map(cap).join("-");
  const sprite = p.name.replace(/[^a-z0-9]/g, "");

  return {
    id: p.id,
    name,
    sprite,
    type1: types[0],
    type2: types[1] || null,
    hp: stats.hp,
    atk: stats.attack,
    def: stats.defense,
    spa: stats["special-attack"],
    spd: stats["special-defense"],
    spe: stats.speed,
    moves: moveNames,
  };
}

async function fetchSpecies(id) {
  const s = await fetchJSON(`https://pokeapi.co/api/v2/pokemon-species/${id}`);
  return {
    id,
    evoChainUrl: s.evolution_chain?.url || null,
    evolvesFromId: s.evolves_from_species ? Number(s.evolves_from_species.url.match(/\/(\d+)\/?$/)[1]) : null,
  };
}

async function pool(items, fn, concurrency) {
  const results = new Array(items.length);
  let idx = 0;
  let done = 0;
  await Promise.all(
    Array.from({ length: concurrency }, async () => {
      while (idx < items.length) {
        const i = idx++;
        try {
          results[i] = await fn(items[i]);
        } catch (e) {
          console.error(`Failed ${items[i]}:`, e.message);
          results[i] = null;
        }
        done++;
        if (done % 50 === 0) console.log(`  ${done}/${items.length}`);
      }
    })
  );
  return results;
}

async function main() {
  const ids = Array.from({ length: TOTAL }, (_, i) => i + 1);

  console.log("Fetching pokemon stats...");
  const mons = (await pool(ids, fetchPokemon, CONCURRENCY)).filter(Boolean);
  console.log(`Got ${mons.length} pokemon`);

  console.log("Fetching species data...");
  const species = (await pool(ids, fetchSpecies, CONCURRENCY)).filter(Boolean);

  console.log("Fetching evolution chains...");
  const chainUrls = [...new Set(species.map((s) => s.evoChainUrl).filter(Boolean))];
  const chains = await pool(chainUrls, (u) => fetchJSON(u), CONCURRENCY);

  const evoMap = {};
  for (const chain of chains) {
    if (!chain) continue;
    const walk = (node) => {
      const fromId = Number(node.species.url.match(/\/(\d+)\/?$/)[1]);
      for (const ev of node.evolves_to) {
        const toId = Number(ev.species.url.match(/\/(\d+)\/?$/)[1]);
        const detail = ev.evolution_details?.[0];
        const lvl = detail?.min_level || (detail?.trigger?.name === "level-up" ? 25 : 30);
        if (!evoMap[fromId]) evoMap[fromId] = { to: toId, at: lvl };
        walk(ev);
      }
    };
    walk(chain.chain);
  }

  for (const m of mons) {
    if (evoMap[m.id]) {
      m.canEvolve = evoMap[m.id].to;
      m.evolveAt = evoMap[m.id].at;
    }
  }

  mons.sort((a, b) => a.id - b.id);

  const GEN_RANGES = [
    [1, 151], [152, 251], [252, 386], [387, 493], [494, 649],
    [650, 721], [722, 809], [810, 905], [906, 1025],
  ];
  const genOf = (id) => GEN_RANGES.findIndex(([a, b]) => id >= a && id <= b) + 1;

  const lines = [
    "// AUTO-GENERATED by scripts/fetch-pokemon.mjs — do not edit by hand",
    "export type PokemonTemplate = {",
    "  id: number; name: string; sprite: string;",
    "  type1: string; type2: string | null;",
    "  hp: number; atk: number; def: number; spa: number; spd: number; spe: number;",
    "  moves: string[];",
    "  canEvolve?: number; evolveAt?: number;",
    "  gen: number;",
    "};",
    "",
    "export const ALL_POKEMON: PokemonTemplate[] = [",
  ];

  for (const m of mons) {
    const obj = {
      id: m.id, name: m.name, sprite: m.sprite,
      type1: m.type1, type2: m.type2,
      hp: m.hp, atk: m.atk, def: m.def, spa: m.spa, spd: m.spd, spe: m.spe,
      moves: m.moves,
      ...(m.canEvolve ? { canEvolve: m.canEvolve, evolveAt: m.evolveAt } : {}),
      gen: genOf(m.id),
    };
    lines.push(`  ${JSON.stringify(obj)},`);
  }
  lines.push("];", "");
  lines.push("export const TOTAL_POKEMON = ALL_POKEMON.length;");
  lines.push("export const GEN_NAMES: Record<number,string> = { 1:'Kanto',2:'Johto',3:'Hoenn',4:'Sinnoh',5:'Unova',6:'Kalos',7:'Alola',8:'Galar',9:'Paldea' };");

  const out = "src/lib/pokemon-data.ts";
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, lines.join("\n"));
  console.log(`Wrote ${mons.length} pokemon to ${out}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
